version: '3.8'

services:
  easyproxy:
    build: https://github.com/nzo66/EasyProxy.git
    container_name: easyproxy
    restart: unless-stopped
    networks:
      - proxy
  mfp:
    build: https://github.com/nzo66/mediaflow-proxy.git
    container_name: mfp
    env_file:
      - ./mfp/.env
    restart: unless-stopped
    networks:
      - proxy

volumes:
  npm-data:
  npm-letsencrypt:
  duckdns-data:

networks:
  proxy:
    external: true
